### ISSUE TITLE
Reconcile pattern used in GenericFilesActor vs. GenericWorksActor

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra/curation_concerns#31]
GenericFilesActor uses the pattern from Sufia.  GenericWorksActor uses the pattern from Worthwhile.  Someone needs to decide which pattern to use and make them both use it.

**Comment by jcoyne** [comment]
Worthwhile used the GenericFilesActor from Sufia, so I'm not exactly sure why this is required. They aren't mutually exclusive.

**Comment by flyingzumwalt** [comment]
GenericWorkActor (from worthwhile) makes all of its internal methods chainable while GenericFileActor (from sufia) doesn’t do that.  The mismatch is confusing.  I manually merged all of the novel functionality from Worthwhile::GenericFileActor and Sufia::GenericFile::Actor into CurationConcerns::GenericFileActor and in the process it was easier to start with the code from Sufia.  By contrast, CurationConcerns::Generic**Work**Actor -- **Work** actor, not File Actor -- is pretty much straight out of worthwhile, with PCDM/Hydra::Works stuff added in.

**Comment by jcoyne** [comment]
I think the issue here is that GenericFileActor is really a collection of loosely coupled service methods. The GenericFileController handles calling the methods in the correct sequence.  On the other hand the GenericWorkActor *is* the business logic for the controller with a single entry point.  So, maybe deconstructing GenericFileActor into a bunch of services is the way to go.

**Comment by mjgiarlo** [comment]
Actors are radically different now. Closing.
